# Generated by Django 4.1.2 on 2022-11-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_holding_holding_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='principal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='holding_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invest',
            name='holding_number',
            field=models.IntegerField(default=0),
        ),
    ]
