# Generated by Django 4.1.2 on 2022-11-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_principal_alter_holding_holding_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='principal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='holding',
            name='holding_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
