# Generated by Django 4.1.2 on 2022-11-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_account_principal_alter_holding_holding_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
